### ISSUE TITLE
jupyter notebook in the scrapy-xpath code-server

### ISSUE THREAD

**Issue by Neri-hV** [alfredodeza/scraping-demo#2]
Hello Alfredo,
This is another issue in the code-server of laboratory Parse HTML with Scrapy and XPath
The files:  _persistence.ipynb_ and _scraping-with-htmlparser.ipynb_ only are avaiable in the text editor and not in the jupyter notebool editor.  I wasn't able to modify this because it doesn't work.
![SharedScreenshot](https://user-images.githubusercontent.com/91480391/227550800-06e0eb20-aea8-41ee-ba95-f9282f7c7bf3.jpg)

Could you verify please what happen there?
Thanks.

**Comment by kushtun** [comment]
Likewise, going through the Python/SQL course, get to the Web-scraping section, the page mentions the Jupyter notebook, but there is no link to it. Search on git turns up only this issue.

Course URL:

`https://www.coursera.org/learn/scripting-with-python-sql-for-data-engineering-duke/supplement/xalEx/parsing-techniques-with-htmlparser`

> Use the scraping-with-htmlparser.ipynb file to use HTMLParser to extract data from HTML.

^ Can't be done, no link to the notebook on that page.

**Comment by alfredodeza** [comment]
@kushtun @Neri-hV thanks for highlighting this, I'll get this resolved ASAP

**Comment by alfredodeza** [comment]
@kushtun @Neri-hV I've *removed* the lab and created a _Reading_ that has instructions on how to open the lab with Codespaces with this repository template: https://github.com/alfredodeza/scrapy-xpath 

Feel free to open [the template repository](https://github.com/alfredodeza/scrapy-xpath) to your own GitHub Account and use the updated "Reading: Codespaces LAb: Parse HTML with Scrapy and XPath"

That template has everything for the lab including all dependencies. Please re-open this issue if you are still having problems
